---
- name: Ping both containers
  hosts: com.worker1

  tasks:
    - name: Change ssh port to 9000
      set_fact:
        ansible_port: 9000
    - name: Pinging container-1
      ping:
    - name: Change ssh port to 9001
      set_fact:
        ansible_port: 9001
    - name: Pinging container-2
      ping:
